# insert data related stuff

train:
    experiment:
        output_dirname: "/models/"

    data:
        dataset_name: "imdb"

    model:
        name: "sentiment_dense_nn"
        params: {
            "hidden_units": 16,
            "hidden_layers": 1,
            "num_epochs": 20,
        }
    logging:
        config_path: "/app/logging.yaml"

# predict:
#     model:
#         dirname: "/app/models/imdb"
#         version: "1"

#     logging:
#         config_path: "/app/logging.yaml"
